version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "${APP_PORT:-8000}:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true   # <- equivalente ao tini, sem precisar instalar nada
