"""add professor_id to offerings

Revision ID: 02f54080b574
Revises: 882f7ea9cd22
Create Date: 2025-08-15 10:27:52.135557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02f54080b574'
down_revision = '882f7ea9cd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_offerings_professor_id'), ['professor_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['professor_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'professor', 'convidado'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'professor', 'convidado'),
               existing_nullable=False)

    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_offerings_professor_id'))
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.drop_column('professor_id')

    # ### end Alembic commands ###
